DELETE https://fullstackopen-exercises-2-8qix.onrender.com/api/persons/2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "0-9038405",
    "name": "john becham"
}

###

Get http://localhost:3001/info
