DELETE https://fullstackopen-exercises-2-8qix.onrender.com/api/persons/2

###

POST https://fullstackopen-exercises-2-8qix.onrender.com/api/persons
Content-Type: application/json

{
    "number": "09-9038405",
    "name": "john dalton"
}

###

Get http://localhost:3001/info
