POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "The third blog",
  "author": "Selah",
  "url": "https://google.com",
  "likes": 100
}

###

GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "first",
  "name": "first",
  "password": "123"
}

###
GET http://localhost:3003/api/users
